### ISSUE TITLE
download map to PC

### ISSUE THREAD

**Issue by lichguard** [lichguard/GCM#21]
When user presses buy it should generate a file on his computer with all that city maps images and data dump all the POI and Routes in text file (or excel)

**Comment by lichguard** [comment]
one time download should NOT include tour data (please confirm with Merav / project file)

**Comment by makolath** [comment]
waits on issue #22,
will be downloaded when purchasing city

**Comment by lichguard** [comment]
please note that Malki does not expect that we will be able to show in our app the saved data.

**Comment by makolath** [comment]
so she just wants the map itself?

**Comment by makolath** [comment]
the image?

**Comment by makolath** [comment]
we can consider the existing capability of loading a map from the client resource folder as a "bonus"

**Comment by lichguard** [comment]
she wants the image and all relevant map data dump into a text file.
no need to load it. the "buy" remains unchanged throughout the user life.

yes we can.
so client map loading from a file works but does client map download API work?

**Comment by makolath** [comment]
there is no download API because it depends on the implementation of  "buy".
a one time download should download on buy? or later?
a subscription should allow download at any time?

**Comment by lichguard** [comment]
on one time download ("buy" button), it should immediately download the city maps to PC.
this eliminates any versioning control aside #20 .


"a subscription should allow download at any time?"
good question, i'm not sure. i'd say yes. also should workers be able to download maps?
@meravmazooz  what do you think?
 if you have prepared questions for Malki, please add this one.
