### ISSUE TITLE
Implement catalog button options

### ISSUE THREAD

**Issue by lichguard** [lichguard/GCM#22]
1. Users need to be able to subscribe
2. Users need to be able to renew subscription with discount

**Comment by makolath** [comment]
what function is the click listener for this buttons

**Comment by lichguard** [comment]
->CatalogWindowFunctions.java"
    ->ButtonCell extends TableCell<City, String>
        ->public void handle()

it decides what buttons was pressed by the button's text.
you may change it however you want, i really don't like that but don't mind if it stays as is

**Comment by makolath** [comment]
should we consider having a single button for a purchase city subscription/one-time at the bottom/top of the page instead of having two buttons each row.
i.e. click on a row, the button will purchase the chosen row

**Comment by lichguard** [comment]
are you asking from code complexity or user experience perspective?

essentially it is 1 click vs (2 clicks + distance) 
of course i'd have to go with the former. Moreover, it is already implemented.

**Comment by makolath** [comment]
my point of view is code complexity.

**Comment by lichguard** [comment]
it should not be a problem anymore. 

now that you have "public void handle()" that can reference its row data, you are free to do anything.

note: if you set textbtn property in the city class to empty, the button in that row will automatically not show up.
